--- TRIGGER PARA LLEVAR UNA BITACORA DE LO QUE ESTA SUCEDIENDO EN UNA BASE DE DATOS
--- OSEA UN REGISTRO SI SE HACE UN INSERT, UN DELETE , O CUALQUIER OTRA ACCION

CREATE TABLE BITACORAS(
  PK_COD_BITACORA NUMBER PRIMARY KEY,
  DESCRIPCION VARCHAR2(2000),
  FECHA_HORA TIMESTAMP,
  USUARIO VARCHAR2(100),
  OPERACION VARCHAR2(50)
);
--- SEQUENCE PARA UTILIZAR COMO PK EN BITACORA
CREATE SEQUENCE SQ_BITACORAS 
START WITH 1
INCREMENT BY 1;

---- CREACION DE TRIGGER 

CREATE OR REPLACE TRIGGER TG_CATEGORIAS_
AFTER INSERT ON CATEGORIES
FOR EACH ROW 
BEGIN
  INSERT INTO BITACORAS VALUES (SQ_BITACORAS.NEXTVAL, 'SE REALIZO UN INSERT EN LA TABLA CATEGORIAS Y EL DATO NUEVO EN EL ID ES : ' || :NEW.CATEGORY_ID || 'Y EL NOMBRE DE LA CATEGORIA ES : '|| :NEW.CATEGORY_NAME, SYSTIMESTAMP, USER,'OPERACION : INSERT' );
END;

--- PROBANDO EL TRIGGER
BEGIN
  INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('BICICLETAS PLAYERAS');
  COMMIT;
END;


---TRANSACCION AUTONOMA 

CREATE OR REPLACE TRIGGER TG_CATEGORIAS_
AFTER INSERT ON CATEGORIES
FOR EACH ROW 
DECLARE 
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO BITACORAS VALUES (SQ_BITACORAS.NEXTVAL, 'SE REALIZO UN INSERT EN LA TABLA CATEGORIAS Y EL DATO NUEVO EN EL ID ES : ' || :NEW.CATEGORY_ID || 'Y EL NOMBRE DE LA CATEGORIA ES : '|| :NEW.CATEGORY_NAME, SYSTIMESTAMP, USER,'OPERACION : INSERT' );
  COMMIT;
  
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
END;

--- PROBANDO EL TRIGGER
BEGIN
  INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('BICICLETAS DE PISTA');
  COMMIT;
END;
