---SET SERVEROUTPUT ON;

DECLARE
  ---NOMBRE_HABITANTE NVARCHAR2(100);
  NOMBRE TBLDEPARTAMENTOS.NOMBREDEPARTAMENTO%TYPE;
  ITERACION NUMBER(10);
  CANTIDAD_DEPARTAMENTOS NUMBER(10);
  ID_DEPARTAMENTO TBLDEPARTAMENTOS.IDDEPARTAMENTO%TYPE;
  ID_PAIS TBLDEPARTAMENTOS.IDPAIS%TYPE;
BEGIN
   SELECT COUNT(NOMBREDEPARTAMENTO) INTO CANTIDAD_DEPARTAMENTOS FROM TBLDEPARTAMENTOS;
   ITERACION:=1; 
   
   LOOP 
      EXIT WHEN ITERACION > CANTIDAD_DEPARTAMENTOS;
      SELECT NOMBREDEPARTAMENTO, IDDEPARTAMENTO,IDPAIS INTO NOMBRE, ID_DEPARTAMENTO, ID_PAIS FROM TBLDEPARTAMENTOS WHERE IDDEPARTAMENTO=ITERACION;
      DBMS_OUTPUT.put_line('NOMBRE DEPARTAMENTO : '||NOMBRE ||',' || ' ID DEL DEPARTAMENTO :' || ID_DEPARTAMENTO ||','|| ' ID DE PAIS : ' || ID_PAIS);
      DBMS_OUTPUT.PUT_LINE('ESTE ES EL ID Y A LA VEZ EL CONTADOR ' || ITERACION);
    
    ITERACION:= ITERACION+1; 
   END LOOP;
   
END;

--- CURSORES 
-- SQL%ROWCOUNT CURSOS IMPLICITO

DECLARE
  NOMBRE TBLDEPARTAMENTOS.NOMBREDEPARTAMENTO%TYPE;
  ITERACION NUMBER(10);
BEGIN
  ITERACION:=1;
  SELECT NOMBREDEPARTAMENTO INTO NOMBRE FROM TBLDEPARTAMENTOS WHERE IDDEPARTAMENTO=ITERACION;
  DBMS_OUTPUT.PUT_LINE(NOMBRE);
  DBMS_OUTPUT.PUT_LINE('CANTIDAD DE REGISTROS : ' || SQL%ROWCOUNT);
END;


--- CURSORES EXPLICITOS

DECLARE 
    NOMBRE_DEPARTAMENTO TBLDEPARTAMENTOS.NOMBREDEPARTAMENTO%TYPE;
    CURSOR CNOMBRE_DEPARTAMENTO IS SELECT NOMBREDEPARTAMENTO FROM TBLDEPARTAMENTOS;
BEGIN
  --- SE ABRE Y SE LE INDICA POSICIONARCE EN EL PRIMER REGISTRO
  OPEN CNOMBRE_DEPARTAMENTO;
  
  LOOP 
    --- FETCH COLOCA EL CURSOR EN EL PRIMER REGISTRO Y LO MUEVE
    FETCH CNOMBRE_DEPARTAMENTO INTO NOMBRE_DEPARTAMENTO;
    
    EXIT WHEN CNOMBRE_DEPARTAMENTO%NOTFOUND;
    ---NOT FOUND RETORNA TRUE OR FALSE , CUANDO YA NO HAYAN REGISTROS QUE RECORRER
    DBMS_OUTPUT.PUT_LINE('EL  NOMBRE DEL DEPARTAMENTO ES : ' || NOMBRE_DEPARTAMENTO);
    
    ---RETORNA EL NUMERO DE FILA POR EL QUE VA EL CURSOR
    DBMS_OUTPUT.PUT_LINE('ESTE ES EL NUMERO DE FILA :' || CNOMBRE_DEPARTAMENTO%ROWCOUNT);
  END LOOP;
  
  CLOSE CNOMBRE_DEPARTAMENTO;
END;


---- UNIENDO VARIAS TABLAS  

DECLARE 
    NOMBRE_DEPARTAMENTO TBLDEPARTAMENTOS.NOMBREDEPARTAMENTO%TYPE;
    NOMBRE_PAIS TBLPAISES.NOMBREPAIS%TYPE;
    ID_PAIS TBLPAISES.IDPAIS%TYPE;
    
    CURSOR CDATOS_DEPARTAMENTO IS
    SELECT 
      TBLDEPARTAMENTOS.NOMBREDEPARTAMENTO, 
      TBLPAISES.IDPAIS, 
      TBLPAISES.NOMBREPAIS 
    FROM TBLDEPARTAMENTOS 
    INNER JOIN TBLPAISES 
    ON TBLDEPARTAMENTOS.IDPAIS = TBLPAISES.IDPAIS ;
BEGIN
  OPEN CDATOS_DEPARTAMENTO;
  
  LOOP 
    FETCH CDATOS_DEPARTAMENTO INTO NOMBRE_DEPARTAMENTO, ID_PAIS, NOMBRE_PAIS;
    
    EXIT WHEN CDATOS_DEPARTAMENTO%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('EL  NOMBRE DEL DEPARTAMENTO ES : ' || NOMBRE_DEPARTAMENTO);
    DBMS_OUTPUT.PUT_LINE('EL  ID DEL PAIS ES : ' || ID_PAIS);
    DBMS_OUTPUT.PUT_LINE('EL  NOMBRE DEL PAIS ES : ' || NOMBRE_PAIS);
    DBMS_OUTPUT.PUT_LINE(CHR(13));---CHR SALTO DE LINEA Y EL 13 ES EL CODIGO DE ASKY DEL VALOR CAMBIO DE LINEA
    
  END LOOP;
  
  CLOSE CDATOS_DEPARTAMENTO;
END;

----- OTRO MODO DE HACER LA CONSULTA DE ARRIBA

DECLARE 
   ---CURSOR
    CURSOR CDATOS_DEPARTAMENTO IS
    SELECT 
      TBLDEPARTAMENTOS.NOMBREDEPARTAMENTO, 
      TBLPAISES.IDPAIS, 
      TBLPAISES.NOMBREPAIS 
    FROM TBLDEPARTAMENTOS 
    INNER JOIN TBLPAISES 
    ON TBLDEPARTAMENTOS.IDPAIS = TBLPAISES.IDPAIS ;
    ---CURSOR
    
    REGISTRO CDATOS_DEPARTAMENTO%ROWTYPE;  ---- SE MAPEA EL NOMBRE Y EL TIPO DE CADA CAMPO
    
BEGIN
  OPEN CDATOS_DEPARTAMENTO;
  
  LOOP 
    FETCH CDATOS_DEPARTAMENTO INTO REGISTRO;
    
    EXIT WHEN CDATOS_DEPARTAMENTO%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('EL  NOMBRE DEL DEPARTAMENTO ES : ' ||REGISTRO.NOMBREDEPARTAMENTO);
    DBMS_OUTPUT.PUT_LINE('EL  ID DEL PAIS ES : ' || REGISTRO.IDPAIS);
    DBMS_OUTPUT.PUT_LINE('EL  NOMBRE DEL PAIS ES : ' || REGISTRO.NOMBREPAIS);
    DBMS_OUTPUT.PUT_LINE(CHR(13));---CHR SALTO DE LINEA Y EL 13 ES EL CODIGO DE ASKY DEL VALOR CAMBIO DE LINEA
    
  END LOOP;
  
  CLOSE CDATOS_DEPARTAMENTO;
END;
