--- GESTION DE EXEPCIONES
DECLARE
  NOMBRE PRODUCTS.PRODUCT_NAME%TYPE;
  FECHA DATE;
  ERROR_CODE NUMBER;
  ERROR_MSG NVARCHAR2(1000);
BEGIN
  FECHA:=SYSDATE;
  
  SELECT PRODUCT_NAME INTO NOMBRE FROM PRODUCTS WHERE PRODUCT_ID=30000;
  
  DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL PRODUCTO CON ID 1 ES : ' || NOMBRE);
  
  EXCEPTION
  
    WHEN TOO_MANY_ROWS THEN 
      ERROR_CODE:= SQLCODE;
      ERROR_MSG:= SQLERRM;
      DBMS_OUTPUT.PUT_LINE('SE RETORNAN MUCHOS REGISTROS EN LA SENTENCIA SELEC INTO.');
      DBMS_OUTPUT.put_line(ERROR_MSG);
      
    WHEN OTHERS THEN 
      ERROR_CODE:= SQLCODE;
      ERROR_MSG:= SQLERRM;
      
      IF(ERROR_CODE = -1858) THEN
        DBMS_OUTPUT.PUT_LINE('SE ESTAN ASIGNANDO TIPOS DE DATOS INCOMPATIBLES');
        DBMS_OUTPUT.PUT_LINE('MENSAJE DE ERROR :' || ERROR_MSG );
        DBMS_OUTPUT.PUT_LINE('CODIGO ERROR :' || ERROR_CODE );
      END IF;
      
      IF (ERROR_CODE = 100) THEN
        DBMS_OUTPUT.PUT_LINE('EL REGISTRO NO FUE ENCONTRADO :');
        DBMS_OUTPUT.PUT_LINE('MENSAJE DE ERROR :' || ERROR_MSG );
        DBMS_OUTPUT.PUT_LINE('CODIGO ERROR :' || ERROR_CODE );
      END IF;
      
      DBMS_OUTPUT.put_line(SQLCODE);
END;