--- GESTION DE TRANSACCIONES

DECLARE

BEGIN
  INSERT INTO BRANDS VALUES (13,'MOUNTAIN BICI');
  COMMIT;
  INSERT INTO BRANDS VALUES (14,'BICI SHOP');
  COMMIT;
  INSERT INTO BRANDS VALUES (15,'ELECTRO BICI');
  COMMIT;
  
  EXCEPTION 
    WHEN DUP_VAL_ON_INDEX THEN
      DBMS_OUTPUT.PUT_LINE('ERROR DE LLAVES PRIMARIAS');
      ROLLBACK; --- DESACE TODOS LOS CAMBIOS
END;

---  

DECLARE

BEGIN
  UPDATE BRANDS SET BRAND_NAME = BRAND_NAME||'2019' WHERE BRAND_ID = 10 OR BRAND_ID=11;
  UPDATE BRANDS SET BRAND_NAME = BRAND_NAME||'2020' WHERE BRAND_ID = 12 OR BRAND_ID=13;
  
  COMMIT;
  SAVEPOINT DATOS_MODIFICADOS; --- PUNTO DE RESTAURACION
  
  UPDATE BRANDS SET BRAND_ID=1, BRAND_NAME = BRAND_NAME||'2021' WHERE BRAND_ID = 14;
  COMMIT;
  SAVEPOINT DATOS_MODIFICADOS;
  
  EXCEPTION 
    WHEN DUP_VAL_ON_INDEX THEN
      DBMS_OUTPUT.PUT_LINE('ERROR DE LLAVES PRIMARIAS');
      ROLLBACK TO SAVEPOINT DATOS_MODIFICADOS; --- DESACE TODOS LOS CAMBIOS
END;

