--- CONSULTANDO LA FECHA Y PASANDOLA AL FORMATO REQUERIDO
SELECT ORDER_DATE, TO_CHAR(TO_DATE(ORDER_DATE,'YYYYMMDD'),'YYYY-MM-DD'), TO_TIMESTAMP(ORDER_DATE,'YYYYMMDD HH:MI:SS') FROM ORDERS;


--- OBTENER UNA SUB CADENA DE UNA CADENA
---- SUBSTR(NOMBRE_CAMPO DE TIPO VARCHAR, APARTIR DE QUE POSICION, CUANTOS CARACTERES DESPUES DE LA POSICION ANTERIOR)
SELECT CATEGORY_NAME, SUBSTR(CATEGORY_NAME,1,5) SUBSTRING FROM CATEGORIES;

