--- CREACION DE SECUENCIAS 
--- ES UN OBJETO QUE CREAMOS PARA PODER UTILIZAR VALORES SECUENCIALES , SE PUEDEN USAR PARA UN CAMPO INCREMENTAL
--- EN ORACLE NO EXISTE UN TIPO DE DATO AUTOINCREMENTABLE, POR LO TANTO LA ALTERNATIVA ES UNA SECUENCIA
-- POR BUENA PRACTICA SE UTILIZA EL PREFIJO SQ
-- primero se usa next_val EN CADA SESION  -- SINO NO FUNCIONA CURRVAL ...
CREATE SEQUENCE SQ_TABLA_CATEGORIAS 
START WITH 5 
INCREMENT BY 1;

INSERT INTO CATEGORIES VALUES(SQ_TABLA_CATEGORIAS.NEXTVAL, 'BICICLETAS MINI');

DECLARE
  VALOR_ACTUAL NUMBER;
  
BEGIN
  VALOR_ACTUAL:= SQ_TABLA_CATEGORIAS.CURRVAL; --- CURRVAL DA EL VALOR ACTUAL DE LA SEQUENCE
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('EL VALOR ACTUAL DE LA SEQUENCE ES: ' || VALOR_ACTUAL);
  
END;