--- ASIGNAR PERMISOS A UNA TABLA DE OTRA DB
--- GRANT SELECT ON BD_CENSO.PAISES TO ADMINISTRADORES;
--- GRANT TIPO_PERMISO ON TABLA TO ROL 

---CONSULTAR PRIVILEGIOS DE UN USUARIO O ROL

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'DB_BICICLETAS';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'ADMINISTRADORES';

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'ADMINISTRADORES';
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'DB_BICICLETAS';


---QUITAR PERMISOS
REVOKE CREATE ANY PROCEDURE, DROP ANY PROCEDURE FROM ADMINISTRADORES;
--- REVOKE PRIVILEGE1, PRIVILEGE2 FROM ROL