   CREATE USER DB_BICICLETAS IDENTIFIED BY 123
   DEFAULT TABLESPACE USERS 
   TEMPORARY TABLESPACE temp 
   QUOTA UNLIMITED ON users;
   
   CREATE ROLE ADMINISTRADORES;
   
   GRANT CREATE SESSION, CREATE ANY TABLE , CREATE ANY PROCEDURE, ALTER ANY TABLE , ALTER ANY PROCEDURE, DROP ANY TABLE, DROP ANY PROCEDURE TO ADMINISTRADORES;
   
   GRANT ADMINISTRADORES TO DB_BICICLETAS;
   
   ---CONSULTA PARA VERIFICIAR LOS ROLES CREADOS
   SELECT * FROM DBA_ROLES;
   
   ---CONSULTAR PRIVILEGIOS ASIGNADOS AL ROL  
     
     SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'ADMINISTRADORES';
     
     ----TAREA 1
    --  INCISO 1 
   CREATE USER usr20161000203 IDENTIFIED BY 20161000203
   DEFAULT TABLESPACE USERS 
   TEMPORARY TABLESPACE temp 
   QUOTA UNLIMITED ON users;
   
    ---INCISO 1.A
    
   CREATE ROLE ROL_ALCALDIAS;
   
   GRANT CREATE SESSION, CREATE ANY TABLE , ALTER ANY TABLE, DROP ANY TABLE, CREATE ANY SEQUENCE , ALTER ANY SEQUENCE , DROP ANY SEQUENCE TO ROL_ALCALDIAS;
    
   GRANT ROL_ALCALDIAS TO usr20161000203;

   
   ---INCISO 1.B
   GRANT CREATE SESSION, CREATE ANY TABLE , ALTER ANY TABLE, DROP ANY TABLE, CREATE ANY SEQUENCE , ALTER ANY SEQUENCE , DROP ANY SEQUENCE TO usr20161000203;
   
   ---INCISO 1.C 
   ----SI se puede , solo verifica los privilegios que ya tiene y si viene un nuevo en la sentencia lo agrega
   
   --- OTORGAR PERMISOS HACIA OTRA TABLA DE OTRA DB, MEDIANTE EL ROL 
   GRANT SELECT ON USR20161000203.TBLDEPARTAMENTOS TO ADMINISTRADORES;
   GRANT SELECT ON USR20161000203.TBLMUNICIPIOS TO ADMINISTRADORES;
   GRANT SELECT ON USR20161000203.TBLPAISES TO DB_BICICLETAS;
   ----GRANT (TIPO PRIVILEGIO SELECT, ALTER, CREATE) ON (LA TABLA) TO (ROLE)
   
   select * from dba_TAB_privs where grantee='ADMINISTRADORES'
   --- CONSULTAR QUE USUARIO ESTA EN QUE ROL
   SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'DB_BICICLETAS';
   
   --- PRIVILEGIOS OTORGADOS DIRECTAMENTE AL USUARIO
   SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'DB_BICICLETAS'
   
   
   