--- TRIGGERS
-- DISPARADOR AUTOMATICO QUE SE ASOCIA A UNA TABLA DE LA DB , SE EJECUTA AUTOMATICO , ANTES O DESPUES DE UN INSERT, UPDATE O DELETE
-- TRIGGERS() TIENE DOS TIPOS DE VARIABLE , NEW AND OLD
--- NEW ESTA DISPONIBLE CON : INSERT , UPDATE
-- OLD ESTA DISPONIBLE CON UPDATE, DELETE
--- NEW OBTIENE LOS VALORES NUEVOS A INSERTAR O MODIFICAR
--- OLD OBTIENE LOS VALORES QUE SE ELIMINARON O MODIFICARON
--- COMO BUENA PRACTICA SE USA EL PREFIJO TG_NAMETRIGGER

-----

CREATE OR REPLACE TRIGGER TG_SQ_TABLA_CATEGORIAS 
BEFORE INSERT ON CATEGORIES
FOR EACH ROW
DECLARE

BEGIN
  :NEW.CATEGORY_ID:= SQ_TABLA_CATEGORIAS.NEXTVAL;
END;


---- COMPROBANDO QUE FUNCIONA
DECLARE

BEGIN
  INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('BICICLETAS URBANAS');
  COMMIT;
END;