CREATE OR REPLACE TRIGGER TG_INSERTA_BRANDS
BEFORE INSERT ON BRANDS
FOR EACH ROW

DECLARE 

BEGIN
--- TRIM ELIMINA TODO LOS ESPACIOS 
--- UPPER CAMBIA A MAYUSCULAS 
  :NEW.BRAND_NAME := TRIM(UPPER(:NEW.BRAND_NAME));
END;

INSERT INTO BRANDS VALUES (18, ' Alpina ');

----- que se ejecute antes de actualizar
CREATE OR REPLACE TRIGGER TG_UPDATE_BRANDS
BEFORE UPDATE ON BRANDS
FOR EACH ROW

DECLARE 

BEGIN
--- TRIM ELIMINA TODO LOS ESPACIOS AL PRINCIPIO Y AL FINAL DE LA CADENA
--- UPPER CAMBIA A MAYUSCULAS 
  :NEW.BRAND_NAME := TRIM(UPPER(:NEW.BRAND_NAME));
END;

BEGIN
  UPDATE BRANDS SET BRAND_NAME='   tn bike' WHERE BRAND_ID=13;
COMMIT;
END;