CREATE OR REPLACE PROCEDURE SP_INSERTA_PRODUCTO (NOMB_PROD VARCHAR2, ID_BRAND NUMBER, CAT_ID NUMBER, 
ANIO_MODELO NUMBER, PRECIO NUMBER,NOMBRE_BRAND VARCHAR2 , MSJ_ERROR OUT VARCHAR2, MSJ_EXITO OUT VARCHAR2) 
IS
  CANTIDAD_REGISTROS NUMBER;
  COD_BRAND NUMBER;
BEGIN 
   SELECT COUNT(*) INTO CANTIDAD_REGISTROS FROM BRANDS WHERE BRAND_ID= ID_BRAND;
   
   IF (CANTIDAD_REGISTROS = 1) THEN
    
    INSERT INTO PRODUCTS (PRODUCT_NAME, BRAND_ID, CATEGORY_ID, MODEL_YEAR, LIST_PRICE) VALUES (NOMB_PROD, ID_BRAND, CAT_ID, ANIO_MODELO, PRECIO);
    COMMIT;
    
    MSJ_EXITO:= 'LA INSERCION DEL PRODUCTO FUE EXITOSA'; 
    
   ELSE  
      SP_INSERTA_BRAND (NOMBRE_BRAND, COD_BRAND);
      
      INSERT INTO PRODUCTS (PRODUCT_NAME, BRAND_ID, CATEGORY_ID, MODEL_YEAR, LIST_PRICE) VALUES (NOMB_PROD, COD_BRAND, CAT_ID, ANIO_MODELO, PRECIO);
      COMMIT;
    
     MSJ_EXITO:= 'LA INSERCION DEL PRODUCTO FUE EXITOSA'; 
      
      
      
   END IF;
   
   
    EXCEPTION 
       WHEN OTHERS THEN
          MSJ_ERROR:= SQLERRM;    
    
END;



--- OTRO PROCEDIMIENTO PARA GUARDAR UN BRAND QUE NO SE ENCONTRE EN PROCEDURE DE ARRIBA

CREATE OR REPLACE PROCEDURE SP_INSERTA_BRAND (NOMBRE_BRAND VARCHAR2, ID_BRAND OUT NUMBER)
IS

BEGIN 
  INSERT INTO BRANDS (BRAND_NAME) VALUES (NOMBRE_BRAND);
  SELECT BRAND_ID INTO ID_BRAND FROM BRANDS WHERE BRAND_NAME = NOMBRE_BRAND;
  COMMIT;
END;



--- PROBANDO 
DECLARE
MSJ_ERROR VARCHAR2(500);
MSJ_EXITO VARCHAR2(500);
BEGIN
  SP_INSERTA_PRODUCTO('BICICLETA DE PRUEBA 1', 30 , 3, 2018, 1234,'BRAND PRUEBA', MSJ_ERROR, MSJ_EXITO);
  DBMS_OUTPUT.PUT_LINE(MSJ_EXITO || ' ' || MSJ_ERROR);
  
END;