--- CREAR UNA FUNCION QUE RETORNE TODAS LOS REGISTROS DE UNA CONSULTA DE VARIAS TABLAS


CREATE OR REPLACE FUNCTION FN_INF_ORDER_CLIENTES
RETURN SYS_REFCURSOR
IS
  CDATOS SYS_REFCURSOR;
BEGIN
  OPEN CDATOS FOR 
  SELECT 
    ORDERS.ORDER_ID,
    ORDER_DATE,
    TO_DATE(SHIPPED_DATE,'YYYY-MM-DD'),
    CUSTOMERS.CUSTOMER_ID,
    CUSTOMERS.FIRST_NAME,
    CUSTOMERS.LAST_NAME
  FROM ORDERS 
  INNER JOIN CUSTOMERS
  ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;
  
  RETURN CDATOS;
END;

--- PROBANDO ---AHORA SI HACIENDO CON UNA ESTRUCTURA TIPO RECORD
DECLARE
  DATOS_CATEGORIA SYS_REFCURSOR;
  
  TYPE FILA IS RECORD(
    ORDER_ID ORDERS.ORDER_ID%TYPE,
    ORDER_DATE ORDERS.ORDER_DATE%TYPE,
    SHIPPED_DATE DATE,
    CUSTOMER_ID CUSTOMERS.CUSTOMER_ID%TYPE,
    FIRST_NAME CUSTOMERS.FIRST_NAME%TYPE,
    LAST_NAME CUSTOMERS.LAST_NAME%TYPE
  );
  
  REGISTRO FILA;
  
BEGIN
  DATOS_CATEGORIA := FN_INF_ORDER_CLIENTES;
  
  LOOP 
    FETCH DATOS_CATEGORIA INTO REGISTRO;
    
    EXIT WHEN DATOS_CATEGORIA%NOTFOUND;
    
    DBMS_OUTPUT.PUT_LINE('ID: '|| REGISTRO.ORDER_ID);
    DBMS_OUTPUT.PUT_LINE('ORDER DATE: '|| REGISTRO.ORDER_DATE);
    DBMS_OUTPUT.PUT_LINE('SHIPPED DATE: '||REGISTRO.SHIPPED_DATE);
    DBMS_OUTPUT.PUT_LINE('CUSTOMER_ID: '|| REGISTRO.CUSTOMER_ID);
    DBMS_OUTPUT.PUT_LINE('FIRST NAME: '|| REGISTRO.FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('LAST NAME: '|| REGISTRO.LAST_NAME);
    DBMS_OUTPUT.PUT_LINE(CHR(13));
  END LOOP;

END;