--- CREAR UNA FUNCION QUE RETORNE TODAS LOS REGISTROS DE UNA CONSULTA DE VARIAS TABLAS


CREATE OR REPLACE FUNCTION FN_INF_ORDER_CLIENTES
RETURN SYS_REFCURSOR
IS
  CDATOS SYS_REFCURSOR;
BEGIN
  OPEN CDATOS FOR 
  SELECT 
    ORDERS.ORDER_ID,
    ORDER_DATE,
    SHIPPED_DATE,
    CUSTOMERS.CUSTOMER_ID,
    CUSTOMERS.FIRST_NAME,
    CUSTOMERS.LAST_NAME
  FROM ORDERS 
  INNER JOIN CUSTOMERS
  ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;
  
  RETURN CDATOS;
END;

--- PROBANDO
DECLARE
  DATOS_CATEGORIA SYS_REFCURSOR;
  ---- PIENSO QUE USAR UNA ESTRUCTURA DE TIPO RECORD , SERIA DE MEJOR PROVECHO, CONSULTAR AL FINAL DE VER TODOS LOS VIDEOS
  ORDER_ID ORDERS.ORDER_ID%TYPE;
  ORDER_DATE ORDERS.ORDER_DATE%TYPE;
  SHIPPED_DATE ORDERS.SHIPPED_DATE%TYPE;
  CUSTOMER_ID CUSTOMERS.CUSTOMER_ID%TYPE;
  FIRST_NAME CUSTOMERS.FIRST_NAME%TYPE;
  LAST_NAME CUSTOMERS.LAST_NAME%TYPE;
  
BEGIN
  DATOS_CATEGORIA := FN_INF_ORDER_CLIENTES;
  
  LOOP 
    FETCH DATOS_CATEGORIA INTO ORDER_ID, ORDER_DATE, SHIPPED_DATE, CUSTOMER_ID, FIRST_NAME, LAST_NAME;
    
    EXIT WHEN DATOS_CATEGORIA%NOTFOUND;
    
    DBMS_OUTPUT.PUT_LINE('ID: '|| ORDER_ID);
    DBMS_OUTPUT.PUT_LINE('ORDER DATE: '|| ORDER_DATE);
    DBMS_OUTPUT.PUT_LINE('SHIPPED DATE: '||SHIPPED_DATE);
    DBMS_OUTPUT.PUT_LINE('CUSTOMER_ID: '|| CUSTOMER_ID);
    DBMS_OUTPUT.PUT_LINE('FIRST NAME: '|| FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('LAST NAME: '|| LAST_NAME);
    DBMS_OUTPUT.PUT_LINE(CHR(13));
  END LOOP;

END;