---- FUNCIONES
--- UNA FUNCION SE UTILIZA CUANDO QUEREMOS RETORNAR UN VALOR
--- UN SP SE UTILIZA CUANDO NO QUEREMOS RETORNAR UN VALOR

-- ESTRUCTURA BASICA DE UNA FUNCION

CREATE OR REPLACE FUNCTION <NOMBRE DE FUNCION> (<PARAMETROS>)
RETURN <TIPO DE DATO>
IS

BEGIN


  RETURN <VALOR O VARIABLE A RETORNAR>

  <BLOQUE DE EXCEPCIONES>
END;


---- RETORNAR LA CANTIDAD DE PRODUCTOS

CREATE OR REPLACE FUNCTION FN_CANTIDAD_PRODUCTOS
RETURN NUMBER
IS
  CANTIDAD_PRODUCTOS NUMBER;
BEGIN
      SELECT COUNT(*) INTO CANTIDAD_PRODUCTOS FROM PRODUCTS;
      
      
      RETURN CANTIDAD_PRODUCTOS;
END;


--- HOW TO EXECUTE A FUNCTION

--- TYPE 1
SELECT FN_CANTIDAD_PRODUCTOS FROM DUAL;


---- TYPE 2
SET SERVEROUTPUT ON;

DECLARE
  TOTAL_PRODUCTOS NUMBER;
BEGIN
  TOTAL_PRODUCTOS := FN_CANTIDAD_PRODUCTOS;
  DBMS_OUTPUT.PUT_LINE('CANTIDAD DE PRODUCTOS ES: '|| TOTAL_PRODUCTOS);
END;



---- EJERCICIO PARA OBTENER CATEGORIA

CREATE OR REPLACE FUNCTION FN_OBTENER_CATEGORIA( ID_CAT NUMBER, NOMB_CAT OUT VARCHAR2)
RETURN VARCHAR2
IS
  NOMBRE_CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN
  SELECT CATEGORY_NAME INTO NOMBRE_CATEGORIA FROM CATEGORIES WHERE CATEGORY_ID = ID_CAT;
  NOMB_CAT:= NOMBRE_CATEGORIA;
  RETURN NOMBRE_CATEGORIA;
END;

---- EJECUTAR LA FUNCION
DECLARE 
  NOMBRE CATEGORIES.CATEGORY_NAME%TYPE;
  NOM_PARAMETRO CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN 
  NOMBRE:= FN_OBTENER_CATEGORIA(4, NOM_PARAMETRO);
  
  DBMS_OUTPUT.put_line('EL NOMBRE DE LA CATEGORIA QUE RETORNA LA FUNCION ES: '|| NOMBRE);
  DBMS_OUTPUT.put_line('EL NOMBRE DE LA CATEGORIA QUE RETORNA EL PARAMETRO ES: '|| NOM_PARAMETRO);
END;
