--- CREAR UN SP QUE OBTENGA LA CANTIDAD TOTAL DE PRODUCTOS  SIN RECIBIR PARAMETROS
CREATE OR REPLACE PROCEDURE SP_CANTIDAD_PRODUCTOS 
IS
  CANTIDAD NUMBER;
BEGIN
  SELECT 
    COUNT(*) INTO CANTIDAD FROM PRODUCTS;
    DBMS_OUTPUT.put_line('CANTIDAD TOTAL DE PRODUCTOS: ' || CANTIDAD);
END;

BEGIN
  SP_CANTIDAD_PRODUCTOS;
END;

